### ISSUE TITLE
enable construct call other construct

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#757] opened 2018-11-08 18:39 UTC
```
class AA
    construct(int a)
        this(a,1)
    construct(int a,int b)
```
when a class have more construct and construct is complex will be useful

**Comment by Frotty** [comment] 2018-11-08 18:40
duplicate of https://github.com/wurstscript/WurstScript/issues/413

**Closed by Frotty** 2018-11-08 18:40 UTC
