### ISSUE TITLE
getting object definition fields at compiletime

### ISSUE THREAD

**Issue by rhazarian** [wurstscript/WurstScript#904] opened 2019-10-29 19:45 UTC
This is kind of related to https://github.com/wurstscript/WurstScript/issues/902.

The suggested feature is to implement new compiletime natives such as `compiletimenative public function ObjectDefinition.getInt(string field)`, `compiletimenative public function ObjectDefinition.getString(string field)` and so on.

The use case is simple: image I want to create a copy of all standard units (since I cannot modify them, see the issue above), and I want to remove backpack abilities from them. To do it now I should hardcode or generate all abilities of all units... If it was possible to retrieve fields at compiletime, it would be easy to remove the ability from the list.

**Comment by Frotty** [comment] 2019-10-29 21:25
Closing as duplicate of https://github.com/wurstscript/WurstScript/issues/683

Note: You can already get object editing fields that you set yourself by saving them (e.g. hashmap).
However for the default values we would need to read the game's .slk files.

**Closed by Frotty** 2019-10-29 21:25 UTC
