### ISSUE TITLE
Misleading warnings in lambdas expression declaration

### ISSUE THREAD

**Issue by zhylmzr** [wurstscript/WurstScript#965] opened 2020-09-21 09:59 UTC
**Describe the bug**
The compiler reports that constants local should be defined with `let`, but it and lambdas expression cannot automatically infer conflicts.

```
@Test public function foo()
	Predicate<int> pred = (v) -> v mod 2 == 0
	pred.isTureFor(10)

interface Predicate<T>
	function isTureFor(T t) returns bool
```

![Snipaste_2020-09-21_17-59-05](https://user-images.githubusercontent.com/15730824/93754339-28216e80-fc34-11ea-8b08-5f9e8a56bcac.png)

**Comment by Frotty** [comment] 2020-09-21 17:05
duplicate of https://github.com/wurstscript/WurstScript/issues/930

**Closed by Frotty** 2020-09-21 17:05 UTC
