### ISSUE TITLE
If you specify "bla.w3x" in wurst.build file, you'll get a filename bla.w3x.w3x

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#763] opened 2018-11-18 18:34 UTC
all in the title

**Comment by Frotty** [comment] 2018-11-18 19:01
then remove .w3x?

**Comment by Cokemonkey11** [comment] 2018-11-18 19:11
Seems like it would be easy to detect this and avoid in wurstscript

**Comment by Frotty** [comment] 2018-11-18 19:18
Then closing as duplicate of https://github.com/wurstscript/WurstScript/issues/699

**Closed by Frotty** 2018-11-18 19:18 UTC
