### ISSUE TITLE
Help with crash investigation

### ISSUE THREAD

**Issue by k33p** [wurstscript/WurstScript#960] opened 2020-07-18 17:43 UTC
Hello,

I have been working on a map the last few months, but recently I hit a wall.
The map crashes when a trigger is evaluated at the start, i.e on the first selling unit event or chat event etc..

I figure out that if the trigger's actions are trivial (i.e some print statements) the map won't crash. In addition, the
crashes are more frequent as the project's size increases; currently it crashes half the time.

I think I am hitting some limit here but I am not sure.

The generated script is~330k lines long and I see a cyc_XYZ function (the name changes) with ~4k lines, 
all triggers' actions start from that cyc_* function.

I know this is very generic, but I would appreciate your help on this.
Thanks,

**Comment by Frotty** [comment] 2020-07-18 17:52
If you see function names I assume you compiled without optimizations, so you should try with them enabled to check if it's really a limit. Also a "cyc" prefixed function means wurst is resolving a cyclic dependency in your code, which you should perhaps address.

Hitting oplimit shouldn't crash the game, so it's also likely a different issue.

**Comment by k33p** [comment] 2020-07-19 08:54
Did a few tests with optimizations enabled, there are still crashes but less frequent. I will try to resolve all cyclic dependencies and see how it goes.

Thanks,

**Comment by anufis** [comment] 2020-07-19 17:23
I've had same issue which went away after resolving cyclic dependencies

**Comment by k33p** [comment] 2020-07-20 19:47
Glad to hear that. Currently I am trying to find and resolve all cyclic dependencies, but at this point this seems hard. 
BTW is this a JASS limitation? If I compile to lua, this wouldn't be a problem correct?

**Comment by Frotty** [comment] 2020-07-20 21:58
> BTW is this a JASS limitation?

oplimit is, but as I mentioned, it doesn't crash the map, only the thread. It's another issue.

> Currently I am trying to find and resolve all cyclic dependencies, but at this point this seems hard.

Just get rid of all `initlater` imports.

**Comment by k33p** [comment] 2020-07-21 12:09
Hmm, I had removed all initlater imports but there are still "cyc" functions. I found a thread at hive, where you can still get them with just functions ([here](https://www.hiveworkshop.com/threads/release-wurstscript-a-wurst-to-jass-compiler-ide.238522/page-20#post-2832427)). 

That's why I was trying to figure out what causes the cyc functions in my code.
I hope I am not missing something obvious.

**Comment by Frotty** [comment] 2020-07-22 07:41
> I hope I am not missing something obvious.

You are. I said the cause is something else 2 times now.

**Comment by k33p** [comment] 2020-07-22 20:46
yeah.. I was focusing on the cyclic functions as I though it was the hint so far.

Anyways, the good news is that with stacktraces disabled there is no crash. Did 10+ runs without any issue (no optimizations & stacktraces, only `-runcompiletimefunctions` and `-injectobjects`).

**Closed** 2020-08-01 11:44 UTC
