### ISSUE TITLE
Start Locations suddenly behave very oddly

### ISSUE THREAD

**Issue by Nichts** [wurstscript/WurstScript#819] opened 2019-03-18 21:43 UTC
Since updating wurst I observed the following:
- Start locations are suddenly randomized
- I tried setting the start location of all players to fixed in wurst.build:
```players:
    - id: 0
      fixedStartLoc: true
    - id: 1
      fixedStartLoc: true
    - id: 2
      fixedStartLoc: true
    - id: 3
      fixedStartLoc: true
    - id: 4
      fixedStartLoc: true
    - id: 5
      fixedStartLoc: true
    - id: 6
      fixedStartLoc: true
    - id: 7
      fixedStartLoc: true
```

This then caused all start locations to be 0,0 (setting true or false both resulted in the start location being 0,0)

**Comment by Frotty** [comment] 2019-03-18 22:04
Hi again

> Start locations are suddenly randomized

Shouldn't be the case, and I can't reproduce it.
Did you define them in the map? In your `war3map,j` should be one `DefineStartLocation` for each player. Upload map/way to reproduce.

> I tried setting the start location of all players to fixed in wurst.build:

`fixedStartLoc` is default true, you don't need to specify it. I tried your config and it worked.
Inside compiled.j.txt are `call DefineStartLocation(0,  - 2240.0, 4096.0)` calls and `call SetPlayerStartLocation(Player(0), 0)`.
When I do this ingame:
```
doAfter(2.) ->
			flashEffect(Abilities.blinkTarget, vec2(GetStartLocationX(0), GetStartLocationY(0)))
```

The effect shows at the position I placed the start location in the editor.

**Comment by Nichts** [comment] 2019-03-18 22:34
So compiled.j.txt says:
```
	call DefineStartLocation(0,  - 2304.0, 6016.0)
	call DefineStartLocation(1,  - 6016.0, 2304.0)
	call DefineStartLocation(2, 2304.0, 6016.0)
	call DefineStartLocation(3, 6016.0, 2304.0)
	call DefineStartLocation(4,  - 6016.0,  - 2304.0)
	call DefineStartLocation(5,  - 2304.0,  - 6016.0)
	call DefineStartLocation(6, 6016.0,  - 2304.0)
	call DefineStartLocation(7, 2304.0,  - 6016.0)
	call DefineStartLocation(8, 7168.0,  - 7104.0)
	call DefineStartLocation(9,  - 7168.0, 7168.0)
	call DefineStartLocation(10, 7168.0, 7168.0)
```

Which is correct (in all cases only the actual start location and output of getStartLocation() changes).

But running the map with the following module (for testing this is the only wurst file in the whole project)



```
package foo

import ClosureTimers

init
    doAfter(2.0) ->
        for i = 0 to 7
            print(i.toString() + ": " + players[i].getStartLocation().x.toString() + ", " + players[i].getStartLocation().y.toString())
```

prints:

**0: 6016.000, 2304.000**
1: -6016.000, 2304.000
2: 2304.000, 6016.000
**3: 6016.000, 2304.000**
4: -6016.000, -2304.000
5: -2304.000, -6016.000
6: 6016.000, -2304.000
7: 2304.000, -6016.000

Setting fixedStartLoc for all players to true again results in:

0: 0.000, 0.000
1: 0.000, 0.000
2: 0.000, 0.000
3: 0.000, 0.000
4: 0.000, 0.000
5: 0.000, 0.000
6: 0.000, 0.000
7: 0.000, 0.000

(Also tried reinstalling wurst - did not help)

**Comment by Frotty** [comment] 2019-03-18 22:52
> So compiled.j.txt says:

And `SetPlayerStartLocation` calls?

> But running the map with the following module (for testing this is the only wurst file in the whole project)

Are `GetPlayerStartLocationX` and `GetStartLocationX` the same?

> (Also tried reinstalling wurst - did not help)

I don't think that's ever necessary.

Just to be sure:
Map config only get applied on `buildmap` not `runmap` so if you get different results on fixedStartLoc vs non fixed, you run the built map, not just use `runmap`?

I did this and for me it works, so what we really need is a reproducible example, so I can make the issue happen on my machine.

**Comment by Nichts** [comment] 2019-03-19 19:44
So I created a sample project https://github.com/Nichts/wc3_playground but now more weird things are happening:
- On osx things are still broken like I described
- Building the map resets the contents of wurst.build
- The sample map builds and runs fine (with the correct start locations) on Windows iff you run it from vscode directly
- If you build the map on Windows and copy it to the download folder of wc3 and then try to run it it does not work at all (Shows 0 players and wc3 crashes if you select it) - but copying and running WurstRunMap.w3x works normally

**Comment by Frotty** [comment] 2019-03-19 21:20
> Building the map resets the contents of wurst.build

Then you are either building/creating with different versions or your format is incorrect (and hence not read).

> The sample map builds and runs fine (with the correct start locations) on Windows iff you run it from vscode directly

As I wrote above the config is not applied upon run. Only upon build.

> If you build the map on Windows and copy it to the download folder of wc3 and then try to run it it does not work at all (Shows 0 players and wc3 crashes if you select it) - but copying and running WurstRunMap.w3x works normally

I think that's simply because you didn't define any force. Also again, `fixedStartLoc: true` is default.
This config works fine:
```yml
  forces:
  - name: DefaultForce1
    playerIds:
    - 0
    - 1
    - 2
    - 3
  - name: DefaultForce2
    playerIds:
    - 4
    - 5
    - 6
    - 7
  players:
  - id: 0
  - id: 1
  - id: 2
  - id: 3
  - id: 4
  - id: 5
  - id: 6
  - id: 7
```
![](https://i.imgur.com/g0cKzUB.jpg)

However I now was able to reproduce startlocations being replaced with 0,0 and the issue is being investigated.

**Comment by Nichts** [comment] 2019-03-19 22:16
> > Building the map resets the contents of wurst.build
> 
> Then you are either building/creating with different versions or your format is incorrect (and hence not read).

Shouldn't the build be aborted with an error in this case instead of potentially throwing away your data? - Also very hard to debug as it does not indicate what is wrong.

> > The sample map builds and runs fine (with the correct start locations) on Windows iff you run it from vscode directly
> 
> As I wrote above the config is not applied upon run. Only upon build.

Makes sense - but why does warcraft crash when selecting the map shouldn't it fall back to the map inherent settings?

Also this is a deviation from old behaviour? Because it used to work by just setting everything in world edit and wurst would just use that.

> However I now was able to reproduce startlocations being replaced with 0,0 and the issue is being investigated.

Nice 👍 

One last question:
How to set multiline scenario descriptions and loading screen texts? I tried something like this:

```
    description: >
      Line 1
      Line 2
```

But it ended up in a single line instead of multiple lines like I expected

**Comment by Frotty** [comment] 2019-03-20 00:09
> Shouldn't the build be aborted with an error in this case instead of potentially throwing away your data? - Also very hard to debug as it does not indicate what is wrong.

yea probably. the final goal is to have errors in vscode for invalid build configs.

> Makes sense - but why does warcraft crash when selecting the map shouldn't it fall back to the map inherent settings?

> Also this is a deviation from old behaviour? Because it used to work by just setting everything in world edit and wurst would just use that.

Before the new wurst.build updates these values weren't ever modified. Now they are and the migration of existing data didn't work properly.
I pushed a fix, please check again.

> One last question:
How to set multiline scenario descriptions and loading screen texts? I tried something like this:

`>` replaces linebreaks with spaces. `|` should work, otherwise you will have to add the linebreaks manually.

**Comment by Nichts** [comment] 2019-03-21 21:19
> > Also this is a deviation from old behaviour? Because it used to work by just setting everything in world edit and wurst would just use that.
> 
> Before the new wurst.build updates these values weren't ever modified. Now they are and the migration of existing data didn't work properly.
> I pushed a fix, please check again.

Just tried it out again: Not setting fixedStartLoc, not setting a player configuration, setting fixedStartLoc to false or true all result in the start location being random instead of fixed (the 0,0 issue is gone though)

> `>` replaces linebreaks with spaces. `|` should work, otherwise you will have to add the linebreaks manually.

Thanks 👍

**Comment by Frotty** [comment] 2019-03-21 21:21
> Just tried it out again: Not setting fixedStartLoc, not setting a player configuration, setting fixedStartLoc to false or true all result in the start location being random instead of fixed (the 0,0 issue is gone though)

Random?

**Comment by Nichts** [comment] 2019-03-21 21:22
Random as in you spawn in one of the other start locations of your team instead of the preset one

**Comment by Frotty** [comment] 2019-03-21 21:30
I see, a call to `ForcePlayerStartLocation` is missing. The reason I didn't notice is because all start locations of allies were same in my test case.

**Comment by Frotty** [comment] 2019-03-21 21:47
Okay, so how it should work:
1. If you only define the player, but not the `fixedStartLoc` flag, it will use what is set in the input map, or the default value of **false** (the doc page was wrong) if the player is new.
2. Setting `fixedStartLoc` to true or false will override what's in the map.

Please report back.

**Comment by Nichts** [comment] 2019-03-22 05:16
Tried it again everything seems to be working as expected

(Updating the project did delete all of my comments from the wurst.build though)

**Comment by Frotty** [comment] 2019-03-22 07:29
> Tried it again everything seems to be working as expected

Yay \o/

> (Updating the project did delete all of my comments from the wurst.build though)

Hm, if your build file can be parsed, it shouldn't be modified. I will check it out, maybe open new ticket.

**Closed by Frotty** 2019-03-22 07:29 UTC
Labels: bug
