### ISSUE TITLE
Warnings in war3map.j

### ISSUE THREAD

**Issue by frederikaalund** [wurstscript/WurstScript#809] opened 2019-02-23 11:42 UTC
Wurst reports errors in the auto-generated war3map.j file:

![image](https://user-images.githubusercontent.com/545423/53285873-86d7eb00-3766-11e9-8ad3-45bc81eff662.png)

Is this intentional? If so, it would be a nice to be able to disable warnings in said file.

### A Little Bit of Context

I'm defining some global variables (the `udg_*` stuff) in the map file (e.g., regions and names of said regions) that I want to use in my Wurst code. These global variables are neatly extracted into the war3map.j file when Wurst is run. Since war3map.j is merely extracted, I don't think that Wurst should report warnings in it. I have no control over the war3map.j code generation.

Side issue: It would be nice to have something like `@extern` for global variables that are not defined in .wurst files but defined in e.g. war3map.j (all the `udg_*` variables). Imagine a freshly cloned repo that doesn't have war3map.j. In said repo, the `udg_*` variables do not exist yet. Therefore, Wurst won't run since all the references to `udg_*` variables can't be resolved. I have to manually extract the war3map.j file first. This is annoying.

**Comment by Frotty** [comment] 2019-02-23 11:51
> I don't think that Wurst should report warnings in it.

Unlike common.j and blizzard.j I didn't add war3map.j to exceptions, since it can contain user code.

> I have no control over the war3map.j code generation.

You somewhat do - it contains GUI and Jass triggers that are in your map, which can have legit warnings.
You could even fix those warnings above by not pre-placing units in your map, but of course that's not a real solution. We should probably just introduce some lint/warning config that can exclude files, rules, etc.

> Imagine a freshly cloned repo that doesn't have war3map.j. In said repo, the `udg_*` variables do not exist yet. Therefore, Wurst won't run since all the references to `udg_*` variables can't be resolved. I have to manually extract the war3map.j file first. This is annoying.

Then your repo is simply setup incorrectly. You are supposed to commit the war3map.j, as it is needed to build the map. Just like the example project and others you will find on github, the war3map.j is included, and thus the variables can be resolved without any extra configuration.
The workflow should be "add preplaced object" -> "save map" -> "run/build to extract war3map.j" -> "use the now available udg_ vars". Not the other way round.

For some extra cases with .e.g. additional natives by YDWE there already exists `@ifNotDefined`

**Comment by frederikaalund** [comment] 2019-02-23 12:31
Thanks for the prompt reply.

> Unlike common.j and blizzard.j I didn't add war3map.j to exceptions, since it can contain user code.

> You somewhat do - it contains GUI and Jass triggers that are in your map, which can have legit warnings.

That is a good point. I guess it is to have compatibility with legacy maps written in JASS.

> You could even fix those warnings above by not pre-placing units in your map, but of course that's not a real solution.

Yeah, I'd like to avoid that. I really like current work flow with pre-placed units and pre-defined regions.

> Then your repo is simply setup incorrectly. You are supposed to commit the war3map.j, as it is needed to build the map.

Ah, well if that is the way it is supposed to be I'll include war3map.j in the repo. Good to have that cleared up. Cheers.

> But I think a separate extraction command couldn't hurt.

This way, both work flows (the one I'm using now and the one that you propose) are supported. I'd personally like that. In my experience, if I add auto-generated files to the repo, I'll have a noisy git log. E.g., with tons of "build: update auto-generated war3map.j" commits. It feels unnecessary.

> there already exists `@ifNotDefined` but idk if it works as you want to.

A recent langauge addition, I see. Thanks for bringing it to my attention. It could indeed by used in my workflow. It would be nice to have it work for variables too. E.g., `@ifNotDefined rect udg_main_area = null`.

Thanks again for your prompt and detailed response.

**Comment by Frotty** [comment] 2019-02-23 13:34
> I add auto-generated files to the repo, I'll have a noisy git log. E.g., with tons of "build: update auto-generated war3map.j" commits. It feels unnecessary.

I simply don't commit the war3map.j unless I have changed it. The editor writes the last save date into the comment header, which is why it changes on every save.

> A recent langauge addition, I see. Thanks for bringing it to my attention. It could indeed by used in my workflow. It would be nice to have it work for variables too. E.g., `@ifNotDefined rect udg_main_area = null`.
Thanks again for your prompt and detailed response.

🍰  Okay then I'm gonna close this as duplicate of https://github.com/wurstscript/WurstScript/issues/797 ?
You can make a new ticket for ifNotDefined for globals.

**Comment by frederikaalund** [comment] 2019-02-23 13:45
> 🍰 Okay then I'm gonna close this as duplicate of #797 ?

Sounds fine with me.

> You can make a new ticket for ifNotDefined for globals.

I'll do that.

Cheers!

**Comment by frederikaalund** [comment] 2019-03-05 19:33
@Frotty Thanks for looking into this issue. Unfortunately, the warnings persist even after your latest commit:
![image](https://user-images.githubusercontent.com/545423/53831683-abfa0400-3f85-11e9-901e-a2f786b3ef75.png)

Have I missed something?

**Comment by Frotty** [comment] 2019-03-05 19:40
hm yeah, that was yet another warning.

**Closed** 2019-03-05 19:40 UTC
